import "./globals.css";
import Navbar from "../components/Navbar";
import Background from "../components/Background";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen">
        <Navbar />
        <Background />
        {/* Page content */}
        <main className="relative z-10">{children}</main>
      </body>
    </html>
  );
}
